// MOE Primary Mathematics Syllabus P1-P6
// Aligned to 2021 syllabus (updated Oct 2025), applicable PSLE 2026
// Cross-referenced with: Practicle.sg (MOE-certified), school exam syllabi, textbook chapters

export interface Example {
  question: string;
  solution: string;
}

export interface PracticeQuestion {
  id: string;
  question: string;
  answer: string;
  difficulty: "basic" | "intermediate" | "challenging";
  solution?: string;
  figure?: string;
  options?: string[];
}

export interface Topic {
  id: string;
  name: string;
  chapter?: number;
  summary: string;
  keyPoints: string[];
  methods?: string[];
  examples?: Example[];
  practice?: PracticeQuestion[];
}

export interface GradeContent {
  level: string;
  topics: Topic[];
}

export interface SubjectCurriculum {
  subject: string;
  emoji: string;
  grades: GradeContent[];
}

export const mathCurriculum: SubjectCurriculum = {
  subject: "Math",
  emoji: "📐",
  grades: [
    {
      level: "P1",
      topics: [
        { id: "p1-c1", chapter: 1, name: "Numbers to 10", summary: "Count, read and write numbers to 10. Compare and order.", keyPoints: ["Count to 10", "Compare and order numbers", "Number bonds to 10"], methods: ["Counting objects", "Ten-frame"] },
        { id: "p1-c2", chapter: 2, name: "Addition", summary: "Add numbers within 10 using number bonds.", keyPoints: ["Number bonds of addition", "Addition stories", "Adding zero"], methods: ["Number bonds", "Part-whole model"] },
        { id: "p1-c3", chapter: 3, name: "Subtraction", summary: "Subtract numbers within 10. Fact families.", keyPoints: ["Number bonds of subtraction", "Fact families", "Subtraction stories"], methods: ["Number bonds", "Taking away"] },
        { id: "p1-c4", chapter: 4, name: "Ordinal Numbers", summary: "Name positions using ordinal numbers (1st, 2nd, 3rd...).", keyPoints: ["Name positions (1st to 10th)", "Left to right, right to left", "Position word problems"], methods: ["Ordering in a line"] },
        { id: "p1-c5", chapter: 5, name: "Numbers to 20", summary: "Count, read and write numbers to 20. Place value.", keyPoints: ["Count to 20", "Place value: tens and ones", "Compare and order numbers to 20"], methods: ["Place value chart", "Number line"] },
        { id: "p1-c6", chapter: 6, name: "Addition & Subtraction (to 20)", summary: "Add and subtract within 20 using different methods.", keyPoints: ["Methods of addition to 20", "Methods of subtraction from 20", "Making 10 strategy"], methods: ["Making 10", "Count on/back", "Number bonds"] },
        { id: "p1-c7", chapter: 7, name: "Numbers to 100", summary: "Count to 100. Place value (tens and ones). Number patterns.", keyPoints: ["Count to 100", "Number patterns", "Compare and order to 100", "Place value to 100"], methods: ["Place value chart", "Hundred chart"] },
        { id: "p1-c8", chapter: 8, name: "Addition & Subtraction within 100", summary: "Add and subtract 2-digit numbers with and without renaming.", keyPoints: ["Addition without renaming", "Addition with renaming", "Addition of three numbers", "Subtraction without renaming", "Subtraction with renaming", "Word problems"], methods: ["Column method", "Part-whole model"] },
        { id: "p1-c9", chapter: 9, name: "Multiplication", summary: "Introduction to multiplication as equal groups.", keyPoints: ["Basics of multiplication", "Add equal groups", "Multiplication word problems"], methods: ["Equal groups", "Repeated addition", "Array"] },
        { id: "p1-c10", chapter: 10, name: "Division", summary: "Introduction to division as sharing and grouping.", keyPoints: ["Equal sharing", "Equal grouping", "Division word problems"], methods: ["Sharing equally", "Grouping objects"] },
        { id: "p1-c11", chapter: 11, name: "Shapes", summary: "Identify and classify 2D shapes. Form figures.", keyPoints: ["Common shapes (rectangle, square, triangle, circle)", "Getting to know shapes", "Group shapes", "Half circle and quarter circle", "Form shapes"], methods: ["Shape sorting", "Shape patterns"] },
        { id: "p1-c12", chapter: 12, name: "Length", summary: "Measure and compare lengths in centimetres.", keyPoints: ["Measure length in centimetres", "Compare and order length", "Curves and straight lines"], methods: ["Using a ruler", "Direct comparison"] },
        { id: "p1-c13", chapter: 13, name: "Time", summary: "Tell time to 5 minutes. Use a.m. and p.m.", keyPoints: ["Tell time to 5 minutes", "Tell time using a.m. and p.m.", "Duration of one hour and half an hour"], methods: ["Clock reading"] },
        { id: "p1-c14", chapter: 14, name: "Money", summary: "Recognise and count Singapore coins and notes.", keyPoints: ["Count coins and notes", "Exchange money", "Compare money", "Add money", "Subtract money"], methods: ["Counting on"] },
        { id: "p1-c15", chapter: 15, name: "Picture Graphs", summary: "Make and read simple picture graphs.", keyPoints: ["Make picture graphs", "Read picture graphs", "Answer questions from data"], methods: ["Counting from pictures"] },
      ]
    },
    {
      level: "P2",
      topics: [
        { id: "p2-c1", chapter: 1, name: "Whole Numbers", summary: "Count to 1,000. Place value. Odd and even numbers.", keyPoints: ["Count to 1,000", "Place values up to hundreds", "Compare and order numbers", "Number patterns", "Odd and even numbers"], methods: ["Place value chart", "Number line"] },
        { id: "p2-c2", chapter: 2, name: "Addition", summary: "Add numbers up to 3 digits with renaming.", keyPoints: ["Addition without renaming", "Addition with renaming", "Solve addition word problems"], methods: ["Column method", "Part-whole model"] },
        { id: "p2-c3", chapter: 3, name: "Subtraction", summary: "Subtract numbers up to 3 digits with renaming.", keyPoints: ["Subtraction without renaming", "Subtraction with renaming", "Solve subtraction word problems"], methods: ["Column method", "Comparing model"] },
        { id: "p2-c4", chapter: 4, name: "Multiplication (I)", summary: "Times tables of 2, 5 and 10.", keyPoints: ["Multiplication table of 2", "Multiplication table of 5", "Multiplication table of 10", "Understand doubles", "Multiply by 2, 5, 10"], methods: ["Skip counting", "Array model", "Equal groups"] },
        { id: "p2-c5", chapter: 5, name: "Multiplication (II)", summary: "Times tables of 3 and 4.", keyPoints: ["Multiplication table of 3", "Multiplication table of 4", "Multiply by 3 and 4", "Word problems"], methods: ["Skip counting", "Repeated addition"] },
        { id: "p2-c6", chapter: 6, name: "Division", summary: "Divide by 2, 3, 4, 5 and 10.", keyPoints: ["Division as equal sharing", "Division as equal grouping", "Divide by 2, 3, 4, 5, 10", "Relationship with multiplication"], methods: ["Sharing equally", "Grouping", "Related multiplication facts"] },
        { id: "p2-c7", chapter: 7, name: "Fractions", summary: "Recognise halves, quarters. Like fractions.", keyPoints: ["Recognise halves and quarters", "Write fractions", "Compare and order unit fractions", "Compare and order like fractions", "Add fractions", "Subtract fractions"], methods: ["Fraction bar model", "Equal parts of shapes"] },
        { id: "p2-c8", chapter: 8, name: "Money", summary: "Dollars and cents. Decimal notation for money.", keyPoints: ["Recognise dollars and cents", "Convert money", "Compare money", "Money word problems"], methods: ["Convert to cents", "Decimal notation"] },
        { id: "p2-c9", chapter: 9, name: "Length", summary: "Measure length in metres. Compare and solve problems.", keyPoints: ["Measure length in metres", "Compare and order lengths", "Solve length word problems"], methods: ["Using metre ruler", "Unit comparison"] },
        { id: "p2-c10", chapter: 10, name: "Mass", summary: "Measure mass in kilograms and grams.", keyPoints: ["Measure mass in kilograms", "Measure mass in grams", "Compare and order mass", "Mass word problems"], methods: ["Reading weighing scales"] },
        { id: "p2-c11", chapter: 11, name: "Volume", summary: "Measure volume in litres. Compare and solve problems.", keyPoints: ["Measure volume in litres", "Compare and order volume", "Volume word problems"], methods: ["Reading graduated containers"] },
        { id: "p2-c12", chapter: 12, name: "Time", summary: "Tell time to the minute. Convert hours and minutes.", keyPoints: ["Tell time to the minute", "Measure time in hours and minutes", "Convert time"], methods: ["Clock face", "Timeline"] },
        { id: "p2-c13", chapter: 13, name: "Shapes", summary: "3D shapes. Patterns with shapes.", keyPoints: ["Make patterns with shapes", "3-dimensional shapes (cube, cuboid, cone, cylinder, sphere)", "Getting to know 3D shapes", "Making patterns with 3D shapes"], methods: ["Shape classification", "Faces, edges, vertices"] },
        { id: "p2-c14", chapter: 14, name: "Picture Graphs with Scales", summary: "Read picture graphs with scales. Tally charts.", keyPoints: ["Read picture graphs with scales", "Tally charts", "Solve problems from graphs"], methods: ["Multiply by scale value", "Tallying"] },
      ]
    },
    {
      level: "P3",
      topics: [
        { id: "p3-c1", chapter: 1, name: "Whole Numbers", summary: "Count to 10,000. Place value to thousands.", keyPoints: ["Count to 10,000", "Place values up to thousands", "Compare and order numbers", "Complete number patterns", "Word problems involving 4 operations"], methods: ["Place value chart"] },
        { id: "p3-c2", chapter: 2, name: "Addition", summary: "Add numbers up to 4 digits.", keyPoints: ["Find the sum of 2 numbers", "Add 4-digit numbers", "Solve addition word problems"], methods: ["Column method", "Estimation"] },
        { id: "p3-c3", chapter: 3, name: "Subtraction", summary: "Subtract numbers up to 4 digits.", keyPoints: ["Find the difference between 2 numbers", "Subtract 4-digit numbers", "Solve subtraction word problems"], methods: ["Column method", "Checking by addition"] },
        { id: "p3-c4", chapter: 4, name: "Multiplication", summary: "Times tables 6-9. Multiply up to 3 digits by 1 digit.", keyPoints: ["Multiplication table of 6, 7, 8, 9", "Multiply up to 3 digits by 1-digit", "Multiplication word problems"], methods: ["Long multiplication", "Lattice method"] },
        { id: "p3-c5", chapter: 5, name: "Division", summary: "Divide by 6-9. Division with remainder.", keyPoints: ["Divide by 6, 7, 8, 9", "Divide up to 3 digits by 1 digit without remainder", "Divide with remainder", "Division word problems"], methods: ["Long division", "Grouping"] },
        { id: "p3-c6", chapter: 6, name: "Fractions", summary: "Equivalent fractions. Add and subtract related fractions.", keyPoints: ["Write equivalent fractions", "Simplify a fraction", "Compare and order fractions", "Add 2 related fractions", "Subtract 2 related fractions"], methods: ["Fraction wall", "Common denominator"] },
        { id: "p3-c7", chapter: 7, name: "Money", summary: "Make amounts. Add and subtract money.", keyPoints: ["Make up to $1, $10, $100", "Add money", "Subtract money", "Money word problems"], methods: ["Align decimal points", "Convert units"] },
        { id: "p3-c8", chapter: 8, name: "Angles", summary: "Understand angles. Right, acute and obtuse angles.", keyPoints: ["Understand angles", "Identify right angles", "Identify acute angles", "Identify obtuse angles"], methods: ["Set square to check"] },
        { id: "p3-c9", chapter: 9, name: "Perpendicular & Parallel Lines", summary: "Identify perpendicular, parallel, horizontal and vertical lines.", keyPoints: ["Identify perpendicular lines", "Identify parallel lines", "Identify horizontal and vertical lines"], methods: ["Set square and ruler"] },
        { id: "p3-c10", chapter: 10, name: "Area & Perimeter", summary: "Find area and perimeter of squares and rectangles.", keyPoints: ["Find area in square units/cm²/m²", "Find perimeter in cm/m", "Area and perimeter of squares", "Area and perimeter of rectangles"], methods: ["Count squares", "L × W", "2(L+W)"] },
        { id: "p3-c11", chapter: 11, name: "Length", summary: "Measure in m/cm and km/m. Conversions.", keyPoints: ["Measure length in m and cm", "Measure length in km and m", "Solve length word problems"], methods: ["Unit conversion"] },
        { id: "p3-c12", chapter: 12, name: "Mass", summary: "Measure mass in kg and g. Solve problems.", keyPoints: ["Measure mass in kg and g", "Solve mass word problems"], methods: ["Reading scales", "Unit conversion"] },
        { id: "p3-c13", chapter: 13, name: "Volume", summary: "Measure volume in mL and L. Solve problems.", keyPoints: ["Measure volume in ml", "Measure volume in l and ml", "Solve volume word problems"], methods: ["Reading graduated cylinders", "Unit conversion"] },
        { id: "p3-c14", chapter: 14, name: "Time", summary: "Seconds. 24-hour clock. Duration.", keyPoints: ["Tell time in seconds", "Read the 24-hour clock", "Find starting time, finishing time and duration"], methods: ["Timeline method", "Add/subtract time"] },
        { id: "p3-c15", chapter: 15, name: "Bar Graphs", summary: "Read bar graphs and solve problems.", keyPoints: ["Read bar graphs", "Solve word problems using graphs"], methods: ["Read scale", "Compare bars"] },
      ]
    },
    {
      level: "P4",
      topics: [
        { id: "p4-c1", chapter: 1, name: "Numbers to 100,000", summary: "Place value to ten thousands. Compare, order and round.", keyPoints: ["Count to 100,000", "Place values up to ten thousands", "Compare and order numbers", "Number patterns", "Round to nearest 10, 100, 1,000"], methods: ["Place value chart", "Number line"], practice: [
          { id: "p4c1-1", question: "What is the value of the digit 7 in 47,365?", answer: "7,000", difficulty: "basic", solution: "The 7 is in the thousands place.\nValue = 7 × 1,000 = 7,000" },
          { id: "p4c1-2", question: "Arrange these numbers in order from the smallest to the greatest: 45,012  40,521  45,102  40,215", answer: "40,215, 40,521, 45,012, 45,102", difficulty: "basic", solution: "Compare the ten thousands digit first, then thousands, etc.\n40,215 < 40,521 < 45,012 < 45,102" },
          { id: "p4c1-3", question: "Round 67,849 to the nearest 1,000.", answer: "68,000", difficulty: "intermediate", solution: "Look at the hundreds digit: 8 (≥ 5)\nRound up: 67,849 → 68,000" },
          { id: "p4c1-4", question: "What number is 1,000 more than 99,250?", answer: "100,250", difficulty: "intermediate", solution: "99,250 + 1,000 = 100,250" },
          { id: "p4c1-5", question: "The digit 6 in a 5-digit number has a value of 60,000. The digit 3 is in the hundreds place. The remaining digits are all 5. What is the number?", answer: "65,355", difficulty: "challenging", solution: "6 in ten thousands = 60,000\n3 in hundreds = 300\nRemaining digits (thousands, tens, ones) = 5\nNumber = 65,355" },
          { id: "p4c1-6", question: "Write 40,000 + 3,000 + 50 + 8 in standard form.", answer: "43,058", difficulty: "basic", solution: "40,000 + 3,000 + 0 + 50 + 8 = 43,058\nNote: there are 0 hundreds." },
          { id: "p4c1-7", question: "Estimate 4,876 + 3,215 by rounding each number to the nearest thousand.", answer: "8,000", difficulty: "intermediate", solution: "4,876 ≈ 5,000\n3,215 ≈ 3,000\nEstimate = 5,000 + 3,000 = 8,000" },
        ] },
        { id: "p4-c2", chapter: 2, name: "Factors & Multiples", summary: "Find factors, multiples. Common factors and multiples.", keyPoints: ["Find the factors of a number", "Find common factors", "Find the multiples of a number", "Find common multiples of 2 or 3 numbers"], methods: ["Factor tree", "Listing method", "Divisibility rules"], examples: [{ question: "Find the common factors of 12 and 18.", solution: "Factors of 12: 1, 2, 3, 4, 6, 12\nFactors of 18: 1, 2, 3, 6, 9, 18\nCommon factors: 1, 2, 3, 6" }, { question: "Find the first 3 common multiples of 4 and 6.", solution: "Multiples of 4: 4, 8, 12, 16, 20, 24...\nMultiples of 6: 6, 12, 18, 24, 30...\nFirst 3 common multiples: 12, 24, 36" }], practice: [
          { id: "p4c2-1", question: "List all the factors of 36.", answer: "1, 2, 3, 4, 6, 9, 12, 18, 36", difficulty: "basic", solution: "36 = 1 × 36\n36 = 2 × 18\n36 = 3 × 12\n36 = 4 × 9\n36 = 6 × 6\nFactors: 1, 2, 3, 4, 6, 9, 12, 18, 36" },
          { id: "p4c2-2", question: "Is 7 a factor of 56? Explain.", answer: "Yes", difficulty: "basic", solution: "56 ÷ 7 = 8 (no remainder)\nSo 7 is a factor of 56." },
          { id: "p4c2-3", question: "Find the common factors of 24 and 32.", answer: "1, 2, 4, 8", difficulty: "intermediate", solution: "Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24\nFactors of 32: 1, 2, 4, 8, 16, 32\nCommon factors: 1, 2, 4, 8" },
          { id: "p4c2-4", question: "What is the smallest number that is a common multiple of 3, 4 and 6?", answer: "12", difficulty: "challenging", solution: "Multiples of 3: 3, 6, 9, 12, 15...\nMultiples of 4: 4, 8, 12, 16...\nMultiples of 6: 6, 12, 18...\nSmallest common multiple: 12" },
        ] },
        { id: "p4-c3", chapter: 3, name: "Four Operations of Whole Numbers", summary: "Multiply and divide up to 4 digits. Multi-step problems.", keyPoints: ["Multiply a 4-digit number by 1-digit", "Multiply up to 3-digits by 2-digit", "Divide 4-digits by 1-digit", "Solve multi-step word problems"], methods: ["Long multiplication", "Long division", "Model drawing"], examples: [{ question: "1,248 × 36 = ?", solution: "1,248 × 36\n= 1,248 × 30 + 1,248 × 6\n= 37,440 + 7,488\n= 44,928" }], practice: [
          { id: "p4c3-1", question: "2,456 × 7 = ?", answer: "17,192", difficulty: "basic", solution: "2,456 × 7\n= (2,000 × 7) + (400 × 7) + (50 × 7) + (6 × 7)\n= 14,000 + 2,800 + 350 + 42\n= 17,192" },
          { id: "p4c3-2", question: "8,136 ÷ 4 = ?", answer: "2,034", difficulty: "basic", solution: "8,136 ÷ 4 = 2,034" },
          { id: "p4c3-3", question: "A factory produces 1,250 toys per day. How many toys does it produce in 24 days?", answer: "30,000", difficulty: "intermediate", solution: "1,250 × 24\n= 1,250 × 20 + 1,250 × 4\n= 25,000 + 5,000\n= 30,000 toys" },
          { id: "p4c3-4", question: "9,475 ÷ 6 = ? (Give the answer with remainder)", answer: "1,579 R 1", difficulty: "intermediate", solution: "9,475 ÷ 6 = 1,579 remainder 1\nCheck: 1,579 × 6 = 9,474\n9,475 − 9,474 = 1" },
          { id: "p4c3-5", question: "A school has 1,248 students. They are divided equally into 6 groups. Each group is then split into 4 teams. How many students are in each team?", answer: "52", difficulty: "challenging", solution: "Students per group = 1,248 ÷ 6 = 208\nStudents per team = 208 ÷ 4 = 52" },
        ] },
        { id: "p4-c4", chapter: 4, name: "Tables & Line Graphs", summary: "Complete tables. Read and interpret line graphs.", keyPoints: ["Complete a table with given data", "Read and interpret line graphs", "Identify trends from line graphs"], methods: ["Plot points", "Read scales"], practice: [
          { id: "p4c4-1", question: "A line graph shows the temperature at 8am was 24°C and at 2pm was 32°C. What was the increase in temperature?", answer: "8°C", difficulty: "basic", solution: "Increase = 32 − 24 = 8°C" },
          { id: "p4c4-2", question: "The table shows books read by 4 students: Ali (8), Beth (12), Chris (6), Devi (10). What is the total number of books read?", answer: "36", difficulty: "basic", solution: "Total = 8 + 12 + 6 + 10 = 36 books" },
          { id: "p4c4-3", question: "A line graph shows shop sales: Jan ($400), Feb ($350), Mar ($500), Apr ($450). Between which two months was the greatest increase in sales?", answer: "Feb to Mar", difficulty: "intermediate", solution: "Jan→Feb: decrease of $50\nFeb→Mar: increase of $150\nMar→Apr: decrease of $50\nGreatest increase: Feb to Mar ($150)", options: ["Jan to Feb", "Feb to Mar", "Mar to Apr"] },
          { id: "p4c4-4a", question: "The number of books borrowed from a library each day: Mon (45), Tue (38), Wed (52), Thu (41), Fri (64). On which day were the most books borrowed?", answer: "Friday", difficulty: "intermediate", solution: "Compare all values: 45, 38, 52, 41, 64\nFriday has the highest number (64).", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] },
          { id: "p4c4-4b", question: "The number of books borrowed from a library each day: Mon (45), Tue (38), Wed (52), Thu (41), Fri (64). How many more books were borrowed on Friday than on Tuesday?", answer: "26", difficulty: "intermediate", solution: "Friday − Tuesday = 64 − 38 = 26 more books" },
          { id: "p4c4-5a", question: "Water is heated steadily. The temperatures recorded are:\n0 min → 25°C, 2 min → 40°C, 4 min → 55°C, 6 min → 70°C, 8 min → 85°C, 10 min → 100°C.\nWhat was the temperature after 6 minutes?", answer: "70°C", difficulty: "intermediate", solution: "Read from the data: at 6 min, the temperature is 70°C." },
          { id: "p4c4-5b", question: "Water is heated steadily. The temperatures recorded are:\n0 min → 25°C, 2 min → 40°C, 4 min → 55°C, 6 min → 70°C, 8 min → 85°C, 10 min → 100°C.\nBy how many degrees did the temperature rise every 2 minutes?", answer: "15°C", difficulty: "intermediate", solution: "Rise per 2 min = 40 − 25 = 15°C\nCheck: 55 − 40 = 15°C ✓" },
          { id: "p4c4-5c", question: "Water is heated steadily at a constant rate. The temperatures recorded are:\n0 min → 25°C, 2 min → 40°C, 4 min → 55°C, 6 min → 70°C.\nWhat would the temperature be after 3 minutes?", answer: "47.5°C", difficulty: "challenging", solution: "Rise per 2 min = 15°C\nRise per 1 min = 15 ÷ 2 = 7.5°C\nAfter 3 min = 40 + 7.5 = 47.5°C" },
        ] },
        { id: "p4-c5", chapter: 5, name: "Fractions (I)", summary: "Mixed numbers and improper fractions. Convert between them.", keyPoints: ["Understand mixed numbers", "Understand improper fractions", "Convert mixed numbers to improper fractions and vice versa", "Compare and order fractions"], methods: ["Fraction bar model", "Conversion rules"], examples: [{ question: "Convert 2 3/4 to an improper fraction.", solution: "2 3/4 = (2 × 4 + 3) / 4 = 11/4" }, { question: "Convert 17/5 to a mixed number.", solution: "17 ÷ 5 = 3 remainder 2\n17/5 = 3 2/5" }], practice: [
          { id: "p4c5-1", question: "Convert 3 2/5 to an improper fraction.", answer: "17/5", difficulty: "basic", solution: "3 2/5 = (3 × 5 + 2) / 5 = 17/5" },
          { id: "p4c5-2", question: "Convert 23/6 to a mixed number.", answer: "3 5/6", difficulty: "basic", solution: "23 ÷ 6 = 3 remainder 5\n23/6 = 3 5/6" },
          { id: "p4c5-3", question: "Arrange in order from smallest to largest: 2 1/3, 11/4, 9/4", answer: "9/4, 2 1/3, 11/4", difficulty: "intermediate", solution: "Convert all to improper fractions with common denominator:\n2 1/3 = 7/3 = 28/12\n11/4 = 33/12\n9/4 = 27/12\nOrder: 27/12, 28/12, 33/12\n= 9/4, 2 1/3, 11/4" },
        ] },
        { id: "p4-c6", chapter: 6, name: "Fractions (II)", summary: "Add and subtract fractions. Fraction of a set.", keyPoints: ["Add fractions (unlike denominators)", "Subtract fractions (unlike denominators)", "Understand fraction of a set", "Solve fraction word problems"], methods: ["Common denominator", "Model drawing"], examples: [{ question: "2/3 + 1/4 = ?", solution: "Find common denominator: LCD of 3 and 4 = 12\n2/3 = 8/12\n1/4 = 3/12\n8/12 + 3/12 = 11/12" }, { question: "There are 24 students. 3/8 of them are girls. How many boys are there?", solution: "Girls = 3/8 × 24 = 9\nBoys = 24 - 9 = 15" }], practice: [
          { id: "p4c6-1", question: "3/5 + 1/3 = ?", answer: "14/15", difficulty: "basic", solution: "LCD of 5 and 3 = 15\n3/5 = 9/15\n1/3 = 5/15\n9/15 + 5/15 = 14/15" },
          { id: "p4c6-2", question: "7/8 − 1/2 = ?", answer: "3/8", difficulty: "basic", solution: "LCD of 8 and 2 = 8\n7/8 = 7/8\n1/2 = 4/8\n7/8 − 4/8 = 3/8" },
          { id: "p4c6-3", question: "There are 30 sweets. 2/5 are strawberry-flavoured and 1/3 are grape-flavoured. How many sweets are neither?", answer: "8", difficulty: "intermediate", solution: "Strawberry = 2/5 × 30 = 12\nGrape = 1/3 × 30 = 10\nNeither = 30 − 12 − 10 = 8" },
          { id: "p4c6-4", question: "Ali spent 1/4 of his money on a book and 2/5 on a bag. He had $21 left. How much money did he have at first?", answer: "$60", difficulty: "challenging", solution: "Spent: 1/4 + 2/5 = 5/20 + 8/20 = 13/20\nLeft: 1 − 13/20 = 7/20\n7/20 = $21\n1/20 = $3\n20/20 = $60" },
          { id: "p4c6-5", question: "There are 42 marbles in a bag. 2/7 are red, 1/3 are blue and the rest are green. How many green marbles are there?", answer: "16", difficulty: "intermediate", solution: "Red = 2/7 × 42 = 12\nBlue = 1/3 × 42 = 14\nGreen = 42 − 12 − 14 = 16" },
        ] },
        { id: "p4-c7", chapter: 7, name: "Angles", summary: "Name and measure angles in degrees.", keyPoints: ["Name an angle", "Measure angles in degrees", "Draw angles", "Angles on a straight line = 180°", "Angles at a point = 360°"], methods: ["Protractor reading", "Unknown angle calculation"], practice: [
          { id: "p4c7-1", question: "Two angles on a straight line are 65° and x°. Find x.", answer: "115°", difficulty: "basic", solution: "Angles on a straight line = 180°\nx = 180° − 65° = 115°", figure: `<svg viewBox="0 0 300 130" xmlns="http://www.w3.org/2000/svg"><line x1="20" y1="80" x2="280" y2="80" stroke="#333" stroke-width="2"/><line x1="150" y1="80" x2="95" y2="20" stroke="#333" stroke-width="2"/><circle cx="150" cy="80" r="3" fill="#333"/><path d="M 125 80 A 25 25 0 0 1 128 58" stroke="#10B981" stroke-width="2" fill="none"/><path d="M 175 80 A 25 25 0 0 0 128 58" stroke="#F97316" stroke-width="2" fill="none"/><text x="80" y="72" font-size="14" font-weight="bold" fill="#10B981">65°</text><text x="185" y="65" font-size="14" font-weight="bold" fill="#F97316">x°</text><text x="15" y="95" font-size="12" fill="#666">A</text><text x="270" y="95" font-size="12" fill="#666">B</text><text x="87" y="15" font-size="12" fill="#666">C</text></svg>` },
          { id: "p4c7-2", question: "Three angles at a point are 120°, 95° and y°. Find y.", answer: "145°", difficulty: "intermediate", solution: "Angles at a point = 360°\ny = 360° − 120° − 95° = 145°" },
          { id: "p4c7-3", question: "Angle ABC = 135°. Is it an acute, obtuse or reflex angle?", answer: "Obtuse", difficulty: "basic", solution: "90° < 135° < 180°\nSo angle ABC is an obtuse angle.", options: ["Acute", "Obtuse", "Reflex"] },
          { id: "p4c7-4", question: "Two angles on a straight line are in the ratio 1 : 2. Find the two angles.", answer: "60° and 120°", difficulty: "challenging", solution: "Total = 180°\n1 + 2 = 3 parts\n1 part = 180° ÷ 3 = 60°\n2 parts = 120°\nThe angles are 60° and 120°." },
          { id: "p4c7-5", question: "In the figure, AOB is a straight line. Angle COB = 35° and angle COD = 110°. Find angle DOB.", answer: "75°", difficulty: "intermediate", solution: "Angle COD = angle COB + angle DOB\n110° = 35° + angle DOB\nAngle DOB = 110° − 35° = 75°", figure: `<svg viewBox="0 0 300 180" xmlns="http://www.w3.org/2000/svg"><line x1="20" y1="90" x2="280" y2="90" stroke="#333" stroke-width="2"/><line x1="150" y1="90" x2="200" y2="25" stroke="#333" stroke-width="2"/><line x1="150" y1="90" x2="100" y2="155" stroke="#333" stroke-width="2"/><circle cx="150" cy="90" r="3" fill="#333"/><path d="M 170 90 A 20 20 0 0 0 167 72" stroke="#10B981" stroke-width="2" fill="none"/><path d="M 167 72 A 45 45 0 0 0 132 108" stroke="#F97316" stroke-width="2" fill="none"/><text x="178" y="78" font-size="13" font-weight="bold" fill="#10B981">35°</text><text x="118" y="120" font-size="13" font-weight="bold" fill="#F97316">110°</text><text x="15" y="85" font-size="12" fill="#666">A</text><text x="268" y="85" font-size="12" fill="#666">B</text><text x="200" y="20" font-size="12" fill="#666">C</text><text x="88" y="168" font-size="12" fill="#666">D</text><text x="152" y="105" font-size="12" font-weight="bold" fill="#333">O</text></svg>` },
          { id: "p4c7-6", question: "In the figure, two straight lines cross each other. One of the angles formed is 55°. Find angles a, b and c. (Answer in order: a, b, c)", answer: "125°, 55°, 125°", difficulty: "intermediate", solution: "Vertically opposite angles are equal:\nb = 55° (opposite to given angle)\nAngles on a straight line = 180°:\na = 180° − 55° = 125°\nc = 125° (opposite to a)", figure: `<svg viewBox="0 0 240 160" xmlns="http://www.w3.org/2000/svg"><line x1="20" y1="130" x2="220" y2="30" stroke="#333" stroke-width="2"/><line x1="20" y1="30" x2="220" y2="130" stroke="#333" stroke-width="2"/><circle cx="120" cy="80" r="3" fill="#333"/><text x="128" y="65" font-size="14" font-weight="bold" fill="#10B981">55°</text><text x="88" y="65" font-size="14" font-weight="bold" fill="#F97316">a°</text><text x="88" y="105" font-size="14" font-weight="bold" fill="#6366F1">b°</text><text x="128" y="105" font-size="14" font-weight="bold" fill="#F97316">c°</text></svg>` },
        ] },
        { id: "p4-c8", chapter: 8, name: "Rectangles & Squares", summary: "Properties of rectangles and squares.", keyPoints: ["Properties of rectangles (opposite sides equal, all angles 90°)", "Properties of squares (all sides equal, all angles 90°)", "Find unknown sides", "Diagonal properties"], methods: ["Property identification"], practice: [
          { id: "p4c8-1", question: "A rectangle has a length of 12 cm and a width of 8 cm. Find its perimeter.", answer: "40 cm", difficulty: "basic", solution: "Perimeter = 2 × (12 + 8) = 2 × 20 = 40 cm" },
          { id: "p4c8-2", question: "A rectangle has a perimeter of 46 cm. Its width is 9 cm. Find its length.", answer: "14 cm", difficulty: "intermediate", solution: "Perimeter = 2 × (L + W)\n46 = 2 × (L + 9)\n23 = L + 9\nL = 23 − 9 = 14 cm" },
          { id: "p4c8-3", question: "True or False: A square is a special type of rectangle.", answer: "True", difficulty: "basic", solution: "True. A square has all the properties of a rectangle (4 right angles, opposite sides equal) plus all 4 sides are equal." },
        ] },
        { id: "p4-c9", chapter: 9, name: "Decimals", summary: "Tenths, hundredths, thousandths. Convert to fractions.", keyPoints: ["Understand tenths", "Understand hundredths", "Understand thousandths", "Compare and order decimals", "Number patterns with decimals", "Rounding decimals", "Convert decimal to fraction and vice versa"], methods: ["Place value chart", "Number line"], examples: [{ question: "Express 3/8 as a decimal.", solution: "3/8 = 3 ÷ 8 = 0.375" }], practice: [
          { id: "p4c9-1", question: "What is the value of the digit 4 in 3.046?", answer: "0.04", difficulty: "basic", solution: "The 4 is in the hundredths place.\nValue = 4 × 0.01 = 0.04 (4 hundredths)" },
          { id: "p4c9-2", question: "Arrange in order from smallest: 0.45, 0.405, 0.54, 0.504", answer: "0.405, 0.45, 0.504, 0.54", difficulty: "intermediate", solution: "Compare digit by digit:\n0.405, 0.450, 0.504, 0.540\nOrder: 0.405 < 0.45 < 0.504 < 0.54" },
          { id: "p4c9-3", question: "Round 4.768 to 1 decimal place.", answer: "4.8", difficulty: "basic", solution: "Look at the hundredths digit: 6 (≥ 5)\nRound up: 4.768 → 4.8" },
          { id: "p4c9-4", question: "Express 0.375 as a fraction in its simplest form.", answer: "3/8", difficulty: "intermediate", solution: "0.375 = 375/1000\n375/1000 ÷ 125/125 = 3/8" },
        ] },
        { id: "p4-c10", chapter: 10, name: "Four Operations of Decimals", summary: "Add, subtract, multiply and divide decimals.", keyPoints: ["Add decimals", "Subtract decimals", "Multiply decimals", "Divide decimals", "Solve decimal word problems"], methods: ["Align decimal points", "Estimation"], practice: [
          { id: "p4c10-1", question: "3.45 + 2.678 = ?", answer: "6.128", difficulty: "basic", solution: "  3.450\n+ 2.678\n= 6.128" },
          { id: "p4c10-2", question: "5.2 × 4 = ?", answer: "20.8", difficulty: "basic", solution: "5.2 × 4 = 20.8" },
          { id: "p4c10-3", question: "Sarah bought 3 books at $12.90 each. How much did she pay in total?", answer: "$38.70", difficulty: "intermediate", solution: "3 × $12.90\n= 3 × $12 + 3 × $0.90\n= $36 + $2.70\n= $38.70" },
        ] },
        { id: "p4-c11", chapter: 11, name: "Pie Charts", summary: "Read and interpret pie charts.", keyPoints: ["Read and interpret pie charts", "Find fractions/percentages from pie charts", "Solve problems using pie charts"], methods: ["Calculate fractions of total"], practice: [
          { id: "p4c11-1", question: "A pie chart shows 1/4 of 120 students chose Math as their favourite subject. How many students chose Math?", answer: "30", difficulty: "basic", solution: "1/4 × 120 = 30 students" },
          { id: "p4c11-2", question: "A pie chart shows how 200 students travel to school: 1/2 by bus, 1/5 by car, and the rest walk. How many students walk to school?", answer: "60", difficulty: "intermediate", solution: "Bus = 1/2 × 200 = 100\nCar = 1/5 × 200 = 40\nWalk = 200 − 100 − 40 = 60" },
        ] },
        { id: "p4-c12", chapter: 12, name: "Area & Perimeter", summary: "Area and perimeter of composite figures.", keyPoints: ["Find the length of a square given perimeter/area", "Find unknown side of a rectangle", "Find perimeter of composite figures", "Find area of composite figures", "Solve area and perimeter word problems"], methods: ["Cut and add", "Big minus small", "Break into parts"], examples: [{ question: "A square has a perimeter of 36 cm. Find its area.", solution: "Side = 36 ÷ 4 = 9 cm\nArea = 9 × 9 = 81 cm²" }, { question: "An L-shaped figure is made of two rectangles. The big rectangle is 10 cm × 6 cm. A 4 cm × 3 cm piece is cut from one corner. Find the area.", solution: "Big rectangle area = 10 × 6 = 60 cm²\nCut-out area = 4 × 3 = 12 cm²\nArea of L-shape = 60 - 12 = 48 cm²" }], practice: [
          { id: "p4c12-1", question: "A rectangle has a perimeter of 34 cm. Its length is 12 cm. Find its area.", answer: "60 cm²", difficulty: "basic", solution: "Perimeter = 2(L + W)\n34 = 2(12 + W)\n17 = 12 + W\nW = 5 cm\nArea = 12 × 5 = 60 cm²" },
          { id: "p4c12-2", question: "A square has an area of 64 cm². Find its perimeter.", answer: "32 cm", difficulty: "basic", solution: "Side = √64 = 8 cm\nPerimeter = 4 × 8 = 32 cm" },
          { id: "p4c12-3", question: "A rectangular garden is 20 m long and 15 m wide. A path 2 m wide runs around the inside of the garden. Find the area of the path.", answer: "124 m²", difficulty: "challenging", solution: "Outer area = 20 × 15 = 300 m²\nInner length = 20 − 2 − 2 = 16 m\nInner width = 15 − 2 − 2 = 11 m\nInner area = 16 × 11 = 176 m²\nPath area = 300 − 176 = 124 m²" },
          { id: "p4c12-4", question: "A T-shaped figure is formed by placing a rectangle (8 cm × 3 cm) on top of another rectangle (4 cm × 6 cm), centred. Find the total area of the T-shape.", answer: "48 cm²", difficulty: "intermediate", solution: "Top rectangle = 8 × 3 = 24 cm²\nBottom rectangle = 4 × 6 = 24 cm²\nTotal area = 24 + 24 = 48 cm²" },
          { id: "p4c12-5", question: "The figure shows a rectangle with a square cut from the bottom-left corner. Find the area of the shaded figure.", answer: "87 cm²", difficulty: "intermediate", solution: "Rectangle area = 12 × 8 = 96 cm²\nSquare cut-out = 3 × 3 = 9 cm²\nShaded area = 96 − 9 = 87 cm²", figure: `<svg viewBox="0 0 300 200" xmlns="http://www.w3.org/2000/svg"><rect x="40" y="25" width="200" height="140" fill="#E0F5EC" stroke="#10B981" stroke-width="2"/><rect x="40" y="125" width="50" height="40" fill="white" stroke="#10B981" stroke-width="2" stroke-dasharray="6,3"/><text x="140" y="18" text-anchor="middle" font-size="13" font-weight="bold" fill="#333">12 cm</text><text x="250" y="100" font-size="13" font-weight="bold" fill="#333">8 cm</text><text x="65" y="150" text-anchor="middle" font-size="12" fill="#333">3 cm</text><text x="18" y="150" font-size="12" fill="#333">3 cm</text></svg>` },
          { id: "p4c12-6a", question: "Find the area of the L-shaped figure.", answer: "36 cm²", difficulty: "challenging", solution: "Big rectangle = 10 × 4 = 40 cm²\nCut-out = 4 × 1 = 4 cm²\nArea = 40 − 4 = 36 cm²", figure: `<svg viewBox="0 0 280 155" xmlns="http://www.w3.org/2000/svg"><path d="M 30 15 L 150 15 L 150 40 L 235 40 L 235 120 L 30 120 Z" fill="#E0F5EC" stroke="#10B981" stroke-width="2"/><text x="90" y="11" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">6 cm</text><text x="192" y="35" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">4 cm</text><text x="155" y="32" font-size="11" fill="#333">1 cm</text><text x="245" y="85" font-size="12" font-weight="bold" fill="#333">3 cm</text><text x="132" y="140" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">10 cm</text><text x="12" y="72" font-size="12" font-weight="bold" fill="#333">4 cm</text></svg>` },
          { id: "p4c12-6b", question: "Find the perimeter of the L-shaped figure.", answer: "28 cm", difficulty: "challenging", solution: "Perimeter = 6 + 1 + 4 + 3 + 10 + 4 = 28 cm", figure: `<svg viewBox="0 0 280 155" xmlns="http://www.w3.org/2000/svg"><path d="M 30 15 L 150 15 L 150 40 L 235 40 L 235 120 L 30 120 Z" fill="#E0F5EC" stroke="#10B981" stroke-width="2"/><text x="90" y="11" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">6 cm</text><text x="192" y="35" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">4 cm</text><text x="155" y="32" font-size="11" fill="#333">1 cm</text><text x="245" y="85" font-size="12" font-weight="bold" fill="#333">3 cm</text><text x="132" y="140" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">10 cm</text><text x="12" y="72" font-size="12" font-weight="bold" fill="#333">4 cm</text></svg>` },
        ] },
        { id: "p4-c13", chapter: 13, name: "Nets", summary: "Prisms, pyramids and their nets.", keyPoints: ["Understand prisms and pyramids", "Recognise the nets of geometric figures", "Identify which nets fold into cubes/cuboids", "11 nets of a cube"], methods: ["Cut and fold", "Visualisation"], practice: [
          { id: "p4c13-1", question: "How many different nets can a cube have?", answer: "11", difficulty: "basic", solution: "A cube has exactly 11 different nets.\nEach net is made of 6 connected squares that can fold into a cube." },
          { id: "p4c13-2", question: "A cuboid has length 5 cm, width 3 cm and height 2 cm. How many faces does its net have?", answer: "6", difficulty: "basic", solution: "A cuboid has 6 faces, so its net has 6 rectangles." },
        ] },
        { id: "p4-c14", chapter: 14, name: "Symmetry", summary: "Line symmetry. Complete symmetric figures.", keyPoints: ["Identify symmetric figures", "Check if a straight line is a line of symmetry", "Complete symmetric figures"], methods: ["Folding test", "Mirror line", "Grid method"], practice: [
          { id: "p4c14-1", question: "How many lines of symmetry does a square have?", answer: "4", difficulty: "basic", solution: "A square has 4 lines of symmetry:\n2 through opposite sides, 2 through opposite corners." },
          { id: "p4c14-2", question: "How many lines of symmetry does a rectangle (not a square) have?", answer: "2", difficulty: "basic", solution: "A rectangle has 2 lines of symmetry:\nboth through the midpoints of opposite sides." },
        ] },
      ]
    },
    {
      level: "P5",
      topics: [
        { id: "p5-c1", chapter: 1, name: "Whole Numbers", summary: "Numbers to 1,000,000. Place value to hundred thousands.", keyPoints: ["Count to 1,000,000", "Place values up to hundred thousands", "Compare and order large numbers"], methods: ["Place value chart"] },
        { id: "p5-c2", chapter: 2, name: "Four Operations of Whole Numbers", summary: "Order of operations. Multiply and divide by 10, 100, 1,000.", keyPoints: ["Use order of operations (BODMAS)", "Divide by 10, 100, 1,000 and their multiples", "Multiply by 10, 100, 1,000 and their multiples", "Solve word problems involving 4 operations"], methods: ["BODMAS rule", "Place value shifting"] },
        { id: "p5-c3", chapter: 3, name: "Fractions", summary: "Fractions and decimals conversion.", keyPoints: ["Divide whole numbers to get fractions", "Express fractions as decimals", "Express decimals as fractions"], methods: ["Division", "Place value"] },
        { id: "p5-c4", chapter: 4, name: "Four Operations of Fractions", summary: "Add, subtract, multiply fractions. Word problems.", keyPoints: ["Add mixed numbers", "Subtract mixed numbers", "Multiply a fraction by a whole number", "Multiply 2 fractions", "Multiply a mixed number and a whole number", "Solve fraction word problems"], methods: ["Common denominator", "Model drawing", "Multiply numerators/denominators"] },
        { id: "p5-c5", chapter: 5, name: "Decimals", summary: "Multiply and divide decimals. Convert measurements.", keyPoints: ["Multiply decimals by 10, 100, 1,000", "Multiply decimals by tens, hundreds, thousands", "Divide decimals by 10, 100, 1,000", "Divide decimals by tens, hundreds, thousands", "Convert measurements of length, mass and volume", "Solve decimal word problems"], methods: ["Place value shifting", "Align decimal points"] },
        { id: "p5-c6", chapter: 6, name: "Percentage", summary: "Understand percentage. Convert. Find percentage of quantity.", keyPoints: ["Understand what a percentage is", "Convert fraction ↔ percentage", "Convert decimal ↔ percentage", "Find a percentage part of a whole", "Find percentage in pie charts", "Find discount, GST and annual interest", "Solve percentage word problems"], methods: ["Convert to fraction first", "÷ 100 or × 100", "Unitary method"] },
        { id: "p5-c7", chapter: 7, name: "Rate", summary: "Rate as quantity per unit. Solve rate problems.", keyPoints: ["Express rate as amount per unit", "Find rate, total amount or number of units", "Solve problems with proportional reasoning"], methods: ["Unitary method", "Table of values"] },
        { id: "p5-c8", chapter: 8, name: "Area of Triangle", summary: "Area of triangles. Area of composite figures.", keyPoints: ["Identify the base or height of a triangle", "Relate area of triangle to its rectangle", "Find area of triangle using formula (½ × b × h)", "Find area of composite figures"], methods: ["½ × base × height", "Break into parts"] },
        { id: "p5-c9", chapter: 9, name: "Volume", summary: "Volume of cubes and cuboids. Volume of liquid.", keyPoints: ["Volume in cubic units, cm³ and m³", "Volume of a cube", "Volume of a cuboid", "Volume of liquid in a rectangular tank", "Volume word problems"], methods: ["L × W × H", "Edge³ for cube"] },
        { id: "p5-c10", chapter: 10, name: "Angles", summary: "Angle rules: straight line, point, vertically opposite.", keyPoints: ["Angles on a straight line = 180°", "Angles at a point = 360°", "Vertically opposite angles are equal", "Find unknown angle in a triangle"], methods: ["Angle relationships", "180° - known angles"] },
        { id: "p5-c11", chapter: 11, name: "Properties of Triangles", summary: "Isosceles, equilateral, right-angled triangles.", keyPoints: ["Properties of isosceles triangle", "Properties of right-angled triangle", "Properties of equilateral triangle", "Angle sum of triangle = 180°", "Find unknown angles"], methods: ["Property identification", "Angle sum rule"] },
        { id: "p5-c12", chapter: 12, name: "Properties of Parallelogram, Rhombus & Trapezium", summary: "Special quadrilateral properties.", keyPoints: ["Properties of parallelogram", "Properties of rhombus", "Properties of trapezium", "Find unknown angle in a special quadrilateral"], methods: ["Property identification", "Angle sum = 360°"] },
      ]
    },
    {
      level: "P6",
      topics: [
        { id: "p6-c1", chapter: 1, name: "Fractions", summary: "Divide fractions by fractions. Complex fraction problems.", keyPoints: ["Divide a proper fraction by a whole number", "Divide a whole number by a proper fraction", "Divide a fraction by a fraction", "Solve fraction word problems"], methods: ["Keep-Change-Flip", "Model drawing"], examples: [{ question: "3/4 ÷ 2 = ?", solution: "3/4 ÷ 2 = 3/4 × 1/2 = 3/8" }, { question: "6 ÷ 2/3 = ?", solution: "6 ÷ 2/3 = 6 × 3/2 = 18/2 = 9" }], practice: [
          { id: "p6c1-1", question: "5/6 ÷ 3 = ?", answer: "5/18", difficulty: "basic", solution: "5/6 ÷ 3 = 5/6 × 1/3 = 5/18" },
          { id: "p6c1-2", question: "3/4 ÷ 2/5 = ? Give your answer as a mixed number.", answer: "1 7/8", difficulty: "intermediate", solution: "3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8 = 1 7/8" },
          { id: "p6c1-3", question: "Mrs Lee bought 3/4 kg of flour. She used 2/5 of it to bake a cake. How much flour did she use?", answer: "3/10 kg", difficulty: "intermediate", solution: "2/5 × 3/4 = 6/20 = 3/10 kg" },
        ] },
        { id: "p6-c2", chapter: 2, name: "Ratio", summary: "Equivalent ratios. Relationship with fractions.", keyPoints: ["Understand what a ratio is", "Find equivalent ratios", "Simplify ratios", "Find new ratios", "Relationship between fractions and ratios", "Solve ratio word problems"], methods: ["Model drawing", "Unchanged quantity method", "Units method"], examples: [{ question: "The ratio of boys to girls is 3 : 5. There are 40 students in total. How many boys are there?", solution: "Total units = 3 + 5 = 8\n1 unit = 40 ÷ 8 = 5\nBoys = 3 × 5 = 15" }, { question: "Ali and Ben share $240 in the ratio 3 : 5. Ali then gives $10 to Ben. What is the new ratio?", solution: "Ali = 3/8 × $240 = $90\nBen = 5/8 × $240 = $150\nAfter: Ali = $90 - $10 = $80\nBen = $150 + $10 = $160\nNew ratio = 80 : 160 = 1 : 2" }], practice: [
          { id: "p6c2-1", question: "Simplify the ratio 24 : 36.", answer: "2 : 3", difficulty: "basic", solution: "HCF of 24 and 36 = 12\n24 ÷ 12 : 36 ÷ 12 = 2 : 3" },
          { id: "p6c2-2", question: "The ratio of red beads to blue beads is 2 : 7. There are 63 blue beads. How many red beads are there?", answer: "18", difficulty: "basic", solution: "7 units = 63\n1 unit = 63 ÷ 7 = 9\nRed beads = 2 × 9 = 18" },
          { id: "p6c2-3", question: "Tom and Jerry share some stickers in the ratio 4 : 5. Tom has 12 fewer stickers than Jerry. How many stickers do they have altogether?", answer: "108", difficulty: "intermediate", solution: "Difference = 5 - 4 = 1 unit\n1 unit = 12\nTotal units = 4 + 5 = 9\nTotal stickers = 9 × 12 = 108" },
          { id: "p6c2-4", question: "The ratio of Amy's money to Beth's money was 5 : 3. After Amy spent $40, the ratio became 3 : 3. How much money did Amy have at first?", answer: "$100", difficulty: "challenging", solution: "After spending, ratio is 3:3 = 1:1 (equal)\nBeth's money didn't change.\nBefore: Amy = 5 units, Beth = 3 units\nAfter: Amy = 5u - 40, Beth = 3u\n5u - 40 = 3u\n2u = 40\n1u = 20\nAmy at first = 5 × 20 = $100" },
          { id: "p6c2-5", question: "Dora and Sarah had the same amount of money at first. Dora spent $450 while Sarah received $350 from her grandparents. Sarah had thrice as much money as Dora in the end. How much money did Dora and Sarah have altogether at first?", answer: "$1,700", difficulty: "challenging", solution: "Let each person start with 1u.\nDora after: 1u − 450\nSarah after: 1u + 350\nSarah = 3 × Dora:\n1u + 350 = 3(1u − 450)\n1u + 350 = 3u − 1350\n350 + 1350 = 3u − 1u\n1700 = 2u\nu = 850\nAltogether at first = 850 × 2 = $1,700" },
        ] },
        { id: "p6-c3", chapter: 3, name: "Percentage", summary: "Percentage increase/decrease. Find original value.", keyPoints: ["Find the whole given a part and the percentage", "Find the percentage increase/decrease", "Solve percentage word problems"], methods: ["Original = 100%", "New = 100% ± change%"], examples: [{ question: "A bag costs $120 after a 20% discount. What was the original price?", solution: "After discount = 100% - 20% = 80% of original\n80% → $120\n1% → $120 ÷ 80 = $1.50\n100% → $1.50 × 100 = $150" }, { question: "The price of a book increased from $25 to $30. Find the percentage increase.", solution: "Increase = $30 - $25 = $5\nPercentage increase = 5/25 × 100% = 20%" }] },
        { id: "p6-c4", chapter: 4, name: "Algebra", summary: "Algebraic expressions and simple equations.", keyPoints: ["Interpret simple algebraic expressions", "Solve simple equations", "Solve simple linear equations", "Solve by substitution", "Solve algebra word problems"], methods: ["Substitution", "Balancing method", "Working backwards"], examples: [{ question: "Solve: 3x + 7 = 22", solution: "3x + 7 = 22\n3x = 22 − 7\n3x = 15\nx = 15 ÷ 3\nx = 5" }], practice: [
          { id: "p6c4-1", question: "If y = 4, find the value of 5y − 3.", answer: "17", difficulty: "basic", solution: "5y − 3 = 5(4) − 3 = 20 − 3 = 17" },
          { id: "p6c4-2", question: "Solve: 2x + 9 = 25", answer: "x = 8", difficulty: "basic", solution: "2x + 9 = 25\n2x = 25 − 9 = 16\nx = 16 ÷ 2 = 8" },
          { id: "p6c4-3", question: "Tom is x years old. His father is 4 times as old as Tom. Their total age is 60. Find x.", answer: "12", difficulty: "challenging", solution: "Tom = x, Father = 4x\nx + 4x = 60\n5x = 60\nx = 12\nTom is 12 years old." },
        ] },
        { id: "p6-c5", chapter: 5, name: "Angles in Geometrical Figures", summary: "Find unknown angles in composite figures.", keyPoints: ["Find unknown angle in composite figures", "Use multiple angle properties together", "PSLE-style geometry problems"], methods: ["Step-by-step angle finding", "Mark known angles first"], practice: [
          { id: "p6c5-1", question: "In a triangle, two angles are 48° and 67°. Find the third angle.", answer: "65°", difficulty: "basic", solution: "Angle sum of triangle = 180°\nThird angle = 180° − 48° − 67° = 65°" },
          { id: "p6c5-2", question: "An isosceles triangle has one angle of 40°. This is one of the equal angles. Find the largest angle.", answer: "100°", difficulty: "intermediate", solution: "Two equal angles = 40° each\nLargest angle = 180° − 40° − 40° = 100°" },
        ] },
        { id: "p6-c6", chapter: 6, name: "Circles", summary: "Area and circumference. Semicircle, quarter circle. Composite figures.", keyPoints: ["Find diameter given radius and vice versa", "Estimate area using square grid", "Area and circumference of circle", "Area and perimeter of semicircle", "Area and perimeter of quarter circle", "Composite figures involving circles"], methods: ["π × d, 2πr", "πr²", "Use π = 3.14 or 22/7", "Break into parts"], examples: [{ question: "A circle has a radius of 7 cm. Find its area and circumference. (Use π = 22/7)", solution: "Circumference = 2 × 22/7 × 7 = 44 cm\nArea = 22/7 × 7 × 7 = 154 cm²" }, { question: "Find the perimeter of a semicircle with diameter 14 cm.", solution: "Curved part = ½ × π × d = ½ × 22/7 × 14 = 22 cm\nStraight part = 14 cm\nPerimeter = 22 + 14 = 36 cm" }] },
        { id: "p6-c7", chapter: 7, name: "Volume", summary: "Find unknown dimensions. Volume word problems.", keyPoints: ["Find 1 dimension given volume and other dimensions", "Find edge length of cube given volume", "Find height given volume and base area", "Find face area given volume and 1 dimension", "Volume word problems"], methods: ["V = L × W × H", "V = base area × height", "Working backwards"], practice: [
          { id: "p6c7-1", question: "A cube has a volume of 125 cm³. Find the length of one edge.", answer: "5 cm", difficulty: "basic", solution: "Edge = ∛125 = 5 cm\n(since 5 × 5 × 5 = 125)" },
          { id: "p6c7-2", question: "A cuboid has a volume of 480 cm³. Its length is 12 cm and width is 8 cm. Find its height.", answer: "5 cm", difficulty: "intermediate", solution: "V = L × W × H\n480 = 12 × 8 × H\n480 = 96 × H\nH = 480 ÷ 96 = 5 cm" },
          { id: "p6c7-3", question: "A rectangular tank 30 cm long and 20 cm wide contains water to a height of 15 cm. 3 litres of water are added. Find the new height of water.", answer: "20 cm", difficulty: "challenging", solution: "Original volume = 30 × 20 × 15 = 9,000 cm³\n3 litres = 3,000 cm³\nNew volume = 9,000 + 3,000 = 12,000 cm³\nNew height = 12,000 ÷ (30 × 20) = 12,000 ÷ 600 = 20 cm" },
        ] },
        { id: "p6-c8", chapter: 8, name: "Average", summary: "Calculate average. Find total, missing values.", keyPoints: ["Find average given total and number of data", "Find total given average and number of data", "Find number of data given total and average", "Solve average word problems"], methods: ["Average = Total ÷ Number", "Total = Average × Number", "Before-after method"], examples: [{ question: "The average score of 5 tests is 82. What is the total score?", solution: "Total = Average × Number\nTotal = 82 × 5 = 410" }, { question: "Tom scored 75, 80, 90 and 85 in 4 tests. What score does he need in the 5th test to have an average of 84?", solution: "Total needed = 84 × 5 = 420\nCurrent total = 75 + 80 + 90 + 85 = 330\n5th test = 420 - 330 = 90" }] },
      ]
    },
  ]
};

export function getGradeContent(subject: string, level: string): GradeContent | undefined {
  if (subject === "Math") return mathCurriculum.grades.find(g => g.level === level);
  return undefined;
}

export function getAvailableLevels(subject: string): string[] {
  if (subject === "Math") return mathCurriculum.grades.map(g => g.level);
  return ["P1", "P2", "P3", "P4", "P5", "P6"];
}
